FROM golang:1.21.4  as builder

# WORKDIR /app
# COPY . /app
# RUN go get
# RUN go build -o main main.go

# VERSION COPY
WORKDIR /app
COPY . /app
RUN go get
RUN go build -o bin .

ENTRYPOINT [ "/app/bin" ]
# VERSION COPY

# # Build small image

# FROM alpine:3.18
# WORKDIR /app
# COPY --from=builder /app/main . 
# EXPOSE 8080

# CMD [ "/app/main" ]